package:
  name: "spateo-release"
  version: "1.0.2"

source:
  path: ../
#  git_url: https://github.com/aristoteleo/spateo-release.git
#  git_depth: 1

requirements:
  host:
    - python
    - setuptools
    - vtk==9.2.2
    - numpy==1.23.*
    - cython
    - wrapt==1.14.*
  run:
    - anndata==0.7.5

about:
  home: https://github.com/aristoteleo/spateo-release
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Spateo: multidimensional spatiotemporal modeling of single-cell spatial transcriptomics"

extra:
  recipe-maintainers:
    - Xiaojieqiu